linters-settings:
  errcheck:
    check-type-assertions: true

    check-blank: false

linters:
  enable-all: true
  disable:
    - gochecknoglobals
    - gochecknoinits

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - dupl
        - gosec
        - scopelint
    - path: pkg/tectonic/tectonic.go
      linters:
        - errcheck
        - gosec
        - lll
